# Copyright (c) 2015 Aaron Power
# Use of this source code is governed by the MIT/APACHE2.0 license that can be
# found in the LICENCE-{APACHE, MIT} file.
[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "build.rs"
description = "An ORM for DuckDuckGo."
homepage = "https://github.com/Aaronepower/ddg"
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENCE-APACHE.md", "LICENCE-MIT.md"]
license = "MIT/Apache-2.0"
name = "ddg"
readme = "README.md"
repository = "https://github.com/Aaronepower/ddg.git"
version = "0.2.2"

# For building serde in stable.
[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "0.8"
serde_json = "0.8"

[dependencies.reqwest]
version = "0.2"
optional = true

[dependencies.hyper]
version = "0.9"
optional = true

[features]
default = ["reqwest"]
